# build_config.yaml

# Model configuration
model_file: "exported.onnx"
build_dir: "./build"
output_dir: "yolov8_obb_4w4a_416"
board: "U250"

# Optional configuration files
folding_config_file: null
specialize_layers_config_file: null

# Build parameters
verbose: true
standalone_thresholds: true
auto_fifo_depths: true
split_large_fifos: true
synth_clk_period_ns: 10
target_fps: 90
default_swg_exception: false


# Build steps
build_steps:
  - step_tidy_up
  - step_streamline
  - step_convert_to_hw_layers
  - step_create_dataflow_partition
  - step_specialize_layers
  - step_target_fps_parallelization
  - step_apply_folding_config
  - step_minimize_bit_width
  - step_generate_estimate_reports
  - step_hw_codegen
  - step_hw_ipgen
  - step_set_fifo_depths
  - step_create_stitched_ip
  - step_slr_floorplan
  - step_measure_rtlsim_performance
  - step_out_of_context_synthesis
  - step_synthesize_bitfile
  - step_make_pynq_driver
  - step_deployment_package

# Output types to generate
generate_outputs:
  - ESTIMATE_REPORTS
  - BITFILE
  - PYNQ_DRIVER
  - DEPLOYMENT_PACKAGE
